import type { Principal } from "@nolivendaz/canonical-models";
import { withTenantContext } from "@nolivendaz/database";

const context=(p:Principal)=>({tenantId:p.tenantId,isPlatformAdmin:p.isPlatformAdmin,userId:p.userId});

export async function listMerchants(p:Principal){return withTenantContext(context(p),async c=>(await c.query(`SELECT m.*,count(s.id)::int AS site_count FROM merchants m LEFT JOIN sites s ON s.merchant_id=m.id GROUP BY m.id ORDER BY m.name`)).rows);}
export async function createMerchant(p:Principal,i:{code:string;name:string;legalName?:string|undefined;country?:string|undefined;currency?:string|undefined}){return withTenantContext(context(p),async c=>{const r=(await c.query(`INSERT INTO merchants(tenant_id,code,name,legal_name,country,currency) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[p.tenantId,i.code,i.name,i.legalName??null,i.country??null,i.currency??null])).rows[0];await audit(c,p,"merchant.create","merchant",r?.id,r);return r;});}
export async function listSites(p:Principal,merchantId?:string){return withTenantContext(context(p),async c=>(await c.query(`SELECT s.*,m.name AS merchant_name FROM sites s JOIN merchants m ON m.id=s.merchant_id WHERE ($1::uuid IS NULL OR s.merchant_id=$1) ORDER BY m.name,s.name`,[merchantId??null])).rows);}
export async function createSite(p:Principal,i:{merchantId:string;code:string;name:string;address?:string|undefined;district?:string|undefined;region?:string|undefined;timezone?:string|undefined}){return withTenantContext(context(p),async c=>{const owned=await c.query(`SELECT 1 FROM merchants WHERE id=$1 AND tenant_id=$2`,[i.merchantId,p.tenantId]);if(owned.rowCount!==1)throw new Error("MERCHANT_NOT_FOUND");const r=(await c.query(`INSERT INTO sites(tenant_id,merchant_id,code,name,address,district,region,timezone) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[p.tenantId,i.merchantId,i.code,i.name,i.address??null,i.district??null,i.region??null,i.timezone??"Africa/Kampala"])).rows[0];await audit(c,p,"site.create","site",r?.id,r);return r;});}
export async function listServices(p:Principal){return withTenantContext(context(p),async c=>(await c.query(`SELECT * FROM services WHERE tenant_id IS NULL OR tenant_id=$1 ORDER BY category,name`,[p.tenantId])).rows);}
export async function createService(p:Principal,i:{code:string;name:string;category:string}){return withTenantContext(context(p),async c=>{const r=(await c.query(`INSERT INTO services(tenant_id,code,name,category) VALUES($1,$2,$3,$4) RETURNING *`,[p.tenantId,i.code,i.name,i.category])).rows[0];await audit(c,p,"service.create","service",r?.id,r);return r;});}
export async function listProducts(p:Principal){return withTenantContext(context(p),async c=>(await c.query(`SELECT pr.*,s.name AS service_name,s.code AS service_code FROM products pr JOIN services s ON s.id=pr.service_id WHERE pr.tenant_id IS NULL OR pr.tenant_id=$1 ORDER BY s.name,pr.name`,[p.tenantId])).rows);}
export async function createProduct(p:Principal,i:{serviceId:string;code:string;name:string;currency?:string|undefined;minAmount?:string|undefined;maxAmount?:string|undefined;fixedPrice?:string|undefined;variableAmountAllowed?:boolean|undefined}){return withTenantContext(context(p),async c=>{const svc=await c.query(`SELECT 1 FROM services WHERE id=$1 AND (tenant_id IS NULL OR tenant_id=$2)`,[i.serviceId,p.tenantId]);if(svc.rowCount!==1)throw new Error("SERVICE_NOT_FOUND");const r=(await c.query(`INSERT INTO products(tenant_id,service_id,internal_product_code,name,currency,min_amount,max_amount,fixed_price,variable_amount_allowed) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[p.tenantId,i.serviceId,i.code,i.name,i.currency??null,i.minAmount??null,i.maxAmount??null,i.fixedPrice??null,i.variableAmountAllowed??true])).rows[0];await audit(c,p,"product.create","product",r?.id,r);return r;});}
export async function listRoutes(p:Principal){return withTenantContext(context(p),async c=>(await c.query(`SELECT r.*,s.name AS service_name,pr.name AS product_name,m.name AS merchant_name,pp.name AS primary_provider_name,sp.name AS secondary_provider_name FROM routes r JOIN services s ON s.id=r.service_id LEFT JOIN products pr ON pr.id=r.product_id LEFT JOIN merchants m ON m.id=r.merchant_id JOIN providers pp ON pp.id=r.primary_provider_id LEFT JOIN providers sp ON sp.id=r.secondary_provider_id ORDER BY r.enabled DESC,r.priority,r.created_at DESC`)).rows);}
export async function createRoute(p:Principal,i:{merchantId?:string|undefined;serviceId:string;productId?:string|undefined;country?:string|undefined;region?:string|undefined;currency?:string|undefined;primaryProviderId:string;secondaryProviderId?:string|undefined;priority?:number|undefined;effectiveFrom?:string|undefined;effectiveTo?:string|undefined}){return withTenantContext(context(p),async c=>{if(i.merchantId){const m=await c.query(`SELECT 1 FROM merchants WHERE id=$1 AND tenant_id=$2`,[i.merchantId,p.tenantId]);if(m.rowCount!==1)throw new Error("MERCHANT_NOT_FOUND");}const r=(await c.query(`INSERT INTO routes(tenant_id,merchant_id,service_id,product_id,country,region,currency,primary_provider_id,secondary_provider_id,priority,effective_from,effective_to,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,COALESCE($11::timestamptz,now()),$12,$13) RETURNING *`,[p.tenantId,i.merchantId??null,i.serviceId,i.productId??null,i.country??null,i.region??null,i.currency??null,i.primaryProviderId,i.secondaryProviderId??null,i.priority??100,i.effectiveFrom??null,i.effectiveTo??null,p.userId])).rows[0];await audit(c,p,"route.create","route",r?.id,r);return r;});}
export async function listDevices(p:Principal){return withTenantContext(context(p),async c=>(await c.query(`SELECT d.*,m.name AS merchant_name,s.name AS site_name,COALESCE(json_agg(json_build_object('providerId',dpm.provider_id,'connectorId',dpm.connector_id,'providerDeviceId',dpm.provider_device_id)) FILTER(WHERE dpm.id IS NOT NULL),'[]') AS provider_mappings FROM devices d LEFT JOIN merchants m ON m.id=d.merchant_id LEFT JOIN sites s ON s.id=d.site_id LEFT JOIN device_provider_mappings dpm ON dpm.device_id=d.id GROUP BY d.id,m.name,s.name ORDER BY d.last_seen_at DESC NULLS LAST,d.code`)).rows);}
export async function listPayments(p:Principal){return withTenantContext(context(p),async c=>(await c.query(`SELECT py.*,t.transaction_reference,p.name AS provider_name FROM payments py JOIN transactions t ON t.id=py.transaction_id LEFT JOIN providers p ON p.id=t.provider_id ORDER BY py.created_at DESC LIMIT 500`)).rows);}
export async function listAlerts(p:Principal){return withTenantContext(context(p),async c=>(await c.query(`SELECT a.*,p.name AS provider_name FROM alerts a LEFT JOIN providers p ON p.id=a.provider_id ORDER BY CASE a.severity WHEN 'CRITICAL' THEN 0 WHEN 'HIGH' THEN 1 WHEN 'MEDIUM' THEN 2 WHEN 'LOW' THEN 3 ELSE 4 END,a.created_at DESC LIMIT 500`)).rows);}
export async function setAlertStatus(p:Principal,id:string,status:"ACKNOWLEDGED"|"RESOLVED"|"SUPPRESSED"){return withTenantContext(context(p),async c=>{const r=(await c.query(`UPDATE alerts SET status=$2,acknowledged_by=CASE WHEN $2='ACKNOWLEDGED' THEN $3 ELSE acknowledged_by END,acknowledged_at=CASE WHEN $2='ACKNOWLEDGED' THEN now() ELSE acknowledged_at END,resolved_by=CASE WHEN $2='RESOLVED' THEN $3 ELSE resolved_by END,resolved_at=CASE WHEN $2='RESOLVED' THEN now() ELSE resolved_at END,updated_at=now() WHERE id=$1 RETURNING *`,[id,status,p.userId])).rows[0];if(!r)throw new Error("ALERT_NOT_FOUND");await audit(c,p,"alert.status","alert",id,r);return r;});}
export async function listIncidents(p:Principal){return withTenantContext(context(p),async c=>(await c.query(`SELECT i.*,p.name AS provider_name,pc.name AS connector_name,u.display_name AS owner_name FROM incidents i LEFT JOIN providers p ON p.id=i.provider_id LEFT JOIN provider_connectors pc ON pc.id=i.connector_id LEFT JOIN users u ON u.id=i.owner_user_id ORDER BY CASE i.severity WHEN 'CRITICAL' THEN 0 WHEN 'HIGH' THEN 1 WHEN 'MEDIUM' THEN 2 ELSE 3 END,i.started_at DESC LIMIT 500`)).rows);}
export async function createIncident(p:Principal,i:{title:string;severity:string;summary?:string|undefined;providerId?:string|undefined;connectorId?:string|undefined}){return withTenantContext(context(p),async c=>{const r=(await c.query(`INSERT INTO incidents(tenant_id,incident_number,title,severity,summary,provider_id,connector_id,created_by) VALUES($1,'INC-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,14)),$2,$3,$4,$5,$6,$7) RETURNING *`,[p.tenantId,i.title,i.severity,i.summary??null,i.providerId??null,i.connectorId??null,p.userId])).rows[0];await audit(c,p,"incident.create","incident",r?.id,r);return r;});}
export async function analyticsSummary(p:Principal){return withTenantContext(context(p),async c=>(await c.query(`SELECT (SELECT count(*)::int FROM transactions) AS transaction_count,(SELECT COALESCE(sum(total_amount),0)::text FROM transactions) AS transaction_value,(SELECT count(*)::int FROM transactions WHERE vend_status='FULFILLED') AS fulfilled_count,(SELECT count(*)::int FROM transactions WHERE normalized_status IN ('UNKNOWN','TIMED_OUT')) AS unknown_count,(SELECT count(*)::int FROM refunds WHERE status NOT IN ('COMPLETED','CANCELLED','REJECTED')) AS open_refunds,(SELECT count(*)::int FROM reconciliation_exceptions WHERE status IN ('OPEN','INVESTIGATING')) AS reconciliation_open,(SELECT count(*)::int FROM support_cases WHERE status NOT IN ('RESOLVED','CLOSED')) AS support_open,(SELECT count(*)::int FROM alerts WHERE status IN ('OPEN','ACKNOWLEDGED')) AS alerts_open,(SELECT count(*)::int FROM devices WHERE status='OFFLINE') AS offline_devices`)).rows[0]);}
export async function listUsers(p:Principal){return withTenantContext(context(p),async c=>(await c.query(`SELECT u.id,u.email,u.display_name,u.status,u.is_platform_admin,u.last_login_at,u.created_at,COALESCE(array_agg(r.code) FILTER(WHERE r.id IS NOT NULL),'{}') AS roles FROM users u LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id GROUP BY u.id ORDER BY u.display_name NULLS LAST,u.email`)).rows);}
export async function listRoles(p:Principal){return withTenantContext(context(p),async c=>(await c.query(`SELECT r.id,r.code,r.name,r.description,r.system_defined,COALESCE(array_agg(pe.code ORDER BY pe.code) FILTER(WHERE pe.id IS NOT NULL),'{}') AS permissions FROM roles r LEFT JOIN role_permissions rp ON rp.role_id=r.id LEFT JOIN permissions pe ON pe.id=rp.permission_id WHERE r.tenant_id IS NULL OR r.tenant_id=$1 GROUP BY r.id ORDER BY r.system_defined DESC,r.name`,[p.tenantId])).rows);}
export async function listAudit(p:Principal){return withTenantContext(context(p),async c=>(await c.query(`SELECT al.*,u.display_name AS actor_name,u.email AS actor_email FROM audit_logs al LEFT JOIN users u ON u.id=al.actor_user_id ORDER BY al.created_at DESC LIMIT 1000`)).rows);}

async function audit(c:any,p:Principal,action:string,type:string,id:unknown,state:unknown){await c.query(`INSERT INTO audit_logs(tenant_id,actor_user_id,action,resource_type,resource_id,after_state) VALUES($1,$2,$3,$4,$5,$6::jsonb)`,[p.tenantId,p.userId,action,type,id??null,JSON.stringify(state??{})]);}
