import test from "node:test";
import assert from "node:assert/strict";
import { executeVendSafely,queryRefundStatusSafely,registerProviderAdapterFactory,resolveUnknownTransaction } from "../dist/index.js";

const connector={id:"11111111-1111-4111-8111-111111111111",providerId:"22222222-2222-4222-8222-222222222222",name:"test",environment:"SANDBOX",apiVersion:null,baseUrl:"https://provider.example",authType:"NONE",credentialReference:null,webhookSecretReference:null,timeoutMs:5000,retryPolicy:{},runtimeConfiguration:{endpoints:{initiateVend:"/vend",getVendStatus:"/vend/{reference}"}},healthCheckPath:null,status:"ACTIVE",enabled:true,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};
const secrets={resolve:async()=>"unused"};

test("UNKNOWN recovery queries original provider without re-vending",async()=>{let queried=0,vended=0;registerProviderAdapterFactory("CUSTOM",()=>({connector,getCapabilities:async()=>[],healthCheck:async()=>({status:"HEALTHY",checkedAt:new Date().toISOString()}),initiateVend:async()=>{vended+=1;throw new Error("must not vend");},getVendStatus:async reference=>({providerTransactionId:reference,status:"FULFILLED"}),getTransaction:async reference=>{queried+=1;return{providerTransactionId:reference,transactionStatus:"FULFILLED",vendStatus:"FULFILLED"};},verifyWebhook:async()=>true,normalizeWebhook:async()=>[]}));const result=await resolveUnknownTransaction({id:"33333333-3333-4333-8333-333333333333",providerType:"CUSTOM",connector,providerTransactionId:"provider-123",status:"UNKNOWN"},secrets);assert.equal(result.status,"FULFILLED");assert.equal(queried,1);assert.equal(vended,0);});

test("vend dispatch classifies definitive client rejection as FAILED",async()=>{registerProviderAdapterFactory("CUSTOM",()=>({connector,getCapabilities:async()=>[],healthCheck:async()=>({status:"HEALTHY",checkedAt:new Date().toISOString()}),initiateVend:async()=>{const error=new Error("bad request");error.httpStatus=400;throw error;},getVendStatus:async reference=>({providerTransactionId:reference,status:"UNKNOWN"}),getTransaction:async reference=>({providerTransactionId:reference,transactionStatus:"UNKNOWN",vendStatus:"UNKNOWN"}),verifyWebhook:async()=>true,normalizeWebhook:async()=>[]}));const result=await executeVendSafely("CUSTOM",connector,secrets,{transactionId:"tx",correlationId:"corr",idempotencyKey:"idem-1234",serviceCode:"POWER",amount:"1000",currency:"UGX"});assert.equal(result.outcome,"FAILED");});

test("vend dispatch classifies server ambiguity as UNKNOWN",async()=>{registerProviderAdapterFactory("CUSTOM",()=>({connector,getCapabilities:async()=>[],healthCheck:async()=>({status:"HEALTHY",checkedAt:new Date().toISOString()}),initiateVend:async()=>{const error=new Error("gateway failure");error.httpStatus=502;throw error;},getVendStatus:async reference=>({providerTransactionId:reference,status:"UNKNOWN"}),getTransaction:async reference=>({providerTransactionId:reference,transactionStatus:"UNKNOWN",vendStatus:"UNKNOWN"}),verifyWebhook:async()=>true,normalizeWebhook:async()=>[]}));const result=await executeVendSafely("CUSTOM",connector,secrets,{transactionId:"tx",correlationId:"corr",idempotencyKey:"idem-5678",serviceCode:"POWER",amount:"1000",currency:"UGX"});assert.equal(result.outcome,"UNKNOWN");});

test("refund recovery performs a GET status query and never submits a refund",async()=>{const originalFetch=globalThis.fetch;let method;let url;globalThis.fetch=async(input,init)=>{method=init?.method;url=String(input);return new Response(JSON.stringify({refund:{id:"refund-123",status:"COMPLETED"}}),{status:200,headers:{"content-type":"application/json"}});};try{const refundConnector={...connector,runtimeConfiguration:{endpoints:{initiateVend:"/vend",getVendStatus:"/vend/{reference}",initiateRefund:"/refunds",getRefundStatus:"/refunds/{reference}"},fields:{providerRefundId:"refund.id",refundStatus:"refund.status"}}};const result=await queryRefundStatusSafely(refundConnector,secrets,"refund-123");assert.equal(result.outcome,"CONFIRMED");assert.equal(result.response.status,"COMPLETED");assert.equal(result.response.providerRefundId,"refund-123");assert.equal(method,"GET");assert.match(url,/\/refunds\/refund-123$/);}finally{globalThis.fetch=originalFetch;}});
