"use server";
import { revalidatePath } from "next/cache";
import { apiPatch,apiPost,apiPut } from "../lib/api";
const text=(f:FormData,k:string)=>String(f.get(k)??'').trim();const optional=(f:FormData,k:string)=>{const v=text(f,k);return v||undefined};const list=(v:string)=>v.split(',').map(x=>x.trim()).filter(Boolean);
export async function createMerchantAction(f:FormData){await apiPost('/api/v1/merchants',{code:text(f,'code').toUpperCase(),name:text(f,'name'),...(optional(f,'legalName')?{legalName:optional(f,'legalName')}:{}),...(optional(f,'country')?{country:text(f,'country').toUpperCase()}:{}),...(optional(f,'currency')?{currency:text(f,'currency').toUpperCase()}:{} )});revalidatePath('/merchants')}
export async function createSiteAction(f:FormData){await apiPost('/api/v1/sites',{merchantId:text(f,'merchantId'),code:text(f,'code').toUpperCase(),name:text(f,'name'),...(optional(f,'address')?{address:optional(f,'address')}:{}),...(optional(f,'district')?{district:optional(f,'district')}:{}),...(optional(f,'region')?{region:optional(f,'region')}:{} )});revalidatePath('/merchants')}
export async function createServiceAction(f:FormData){await apiPost('/api/v1/services',{code:text(f,'code').toUpperCase(),name:text(f,'name'),category:text(f,'category')});revalidatePath('/catalog')}
export async function createProductAction(f:FormData){await apiPost('/api/v1/products',{serviceId:text(f,'serviceId'),code:text(f,'code').toUpperCase(),name:text(f,'name'),...(optional(f,'currency')?{currency:text(f,'currency').toUpperCase()}:{}),...(optional(f,'minAmount')?{minAmount:optional(f,'minAmount')}:{}),...(optional(f,'maxAmount')?{maxAmount:optional(f,'maxAmount')}:{}),...(optional(f,'fixedPrice')?{fixedPrice:optional(f,'fixedPrice')}:{}),variableAmountAllowed:f.get('variableAmountAllowed')==='on'});revalidatePath('/catalog')}
export async function createRouteAction(f:FormData){await apiPost('/api/v1/routes',{serviceId:text(f,'serviceId'),primaryProviderId:text(f,'primaryProviderId'),...(optional(f,'merchantId')?{merchantId:optional(f,'merchantId')}:{}),...(optional(f,'productId')?{productId:optional(f,'productId')}:{}),...(optional(f,'country')?{country:text(f,'country').toUpperCase()}:{}),...(optional(f,'region')?{region:optional(f,'region')}:{}),...(optional(f,'currency')?{currency:text(f,'currency').toUpperCase()}:{}),...(optional(f,'secondaryProviderId')?{secondaryProviderId:optional(f,'secondaryProviderId')}:{}),priority:Number(text(f,'priority')||100)});revalidatePath('/routing')}
export async function createProviderAction(f:FormData){await apiPost('/api/v1/providers',{code:text(f,'code').toUpperCase(),name:text(f,'name'),providerType:text(f,'providerType'),scope:'TENANT',...(optional(f,'country')?{country:text(f,'country').toUpperCase()}:{}),supportedCurrencies:list(text(f,'currencies')).map(x=>x.toUpperCase()),supportedRegions:list(text(f,'regions'))});revalidatePath('/providers')}
export async function createConnectorAction(providerId:string,f:FormData){const raw=text(f,'runtimeConfiguration')||'{"endpoints":{}}';let runtime:Record<string,unknown>;try{runtime=JSON.parse(raw) as Record<string,unknown>}catch{throw new Error('Runtime configuration must be valid JSON')}await apiPost(`/api/v1/providers/${providerId}/connectors`,{name:text(f,'name'),environment:text(f,'environment'),baseUrl:text(f,'baseUrl'),authType:text(f,'authType'),...(optional(f,'credentialReference')?{credentialReference:optional(f,'credentialReference')}:{}),...(optional(f,'webhookSecretReference')?{webhookSecretReference:optional(f,'webhookSecretReference')}:{}),timeoutMs:Number(text(f,'timeoutMs')||30000),retryPolicy:{},runtimeConfiguration:runtime,enabled:false});revalidatePath(`/providers/${providerId}`)}
export async function setCapabilitiesAction(providerId:string,connectorId:string,f:FormData){await apiPut(`/api/v1/connectors/${connectorId}/capabilities`,{capabilities:list(text(f,'capabilities'))});revalidatePath(`/providers/${providerId}`)}
export async function lifecycleAction(providerId:string,action:'START_DEVELOPMENT'|'OPEN_SANDBOX'){await apiPost(`/api/v1/providers/${providerId}/lifecycle/advance`,{action});revalidatePath(`/providers/${providerId}`)}
export async function connectorStateAction(providerId:string,connectorId:string,status:'ACTIVE'|'DISABLED'|'MAINTENANCE',enabled:boolean){await apiPatch(`/api/v1/connectors/${connectorId}/preproduction-state`,{status,enabled});revalidatePath(`/providers/${providerId}`)}
export async function healthCheckAction(providerId:string,connectorId:string){await apiPost(`/api/v1/connectors/${connectorId}/health-check`,{providerId});revalidatePath(`/providers/${providerId}`);revalidatePath('/integration-health')}
export async function certificationRunAction(providerId:string,connectorId:string){await apiPost(`/api/v1/connectors/${connectorId}/certification-runs`);revalidatePath(`/providers/${providerId}`)}
export async function certificationApproveAction(providerId:string,runId:string){await apiPost(`/api/v1/certification-runs/${runId}/approve`);revalidatePath(`/providers/${providerId}`)}
export async function createIncidentAction(f:FormData){await apiPost('/api/v1/incidents',{title:text(f,'title'),severity:text(f,'severity'),...(optional(f,'summary')?{summary:optional(f,'summary')}:{}),...(optional(f,'providerId')?{providerId:optional(f,'providerId')}:{} )});revalidatePath('/alerts')}
export async function alertStatusAction(id:string,status:'ACKNOWLEDGED'|'RESOLVED'|'SUPPRESSED'){await apiPatch(`/api/v1/alerts/${id}`,{status});revalidatePath('/alerts')}
export async function provisionUserAction(f:FormData){await apiPost('/api/v1/admin/users',{email:text(f,'email'),...(optional(f,'displayName')?{displayName:optional(f,'displayName')}:{}),isPlatformAdmin:f.get('isPlatformAdmin')==='on'});revalidatePath('/administration')}
export async function userStatusAction(userId:string,status:'ACTIVE'|'SUSPENDED'|'DISABLED'){await apiPatch(`/api/v1/admin/users/${userId}`,{status});revalidatePath('/administration')}
export async function assignRoleAction(f:FormData){await apiPost(`/api/v1/admin/users/${text(f,'userId')}/roles/${text(f,'roleId')}`);revalidatePath('/administration')}
export async function createRoleAction(f:FormData){await apiPost('/api/v1/admin/roles',{code:text(f,'code'),name:text(f,'name'),...(optional(f,'description')?{description:optional(f,'description')}:{}),permissions:list(text(f,'permissions'))});revalidatePath('/administration')}
