import { createHmac, createHash, timingSafeEqual } from "node:crypto";
import type { ConnectorRecord, VendStatus } from "@nolivendaz/canonical-models";

export interface SecretResolver { resolve(reference: string): Promise<string>; }
export class EnvironmentSecretResolver implements SecretResolver { async resolve(reference: string) { if (!reference.startsWith("env://")) throw new Error(`UNSUPPORTED_SECRET_REFERENCE:${reference.split("://")[0] ?? "unknown"}`); const name=reference.slice(6); const value=process.env[name]; if(!value) throw new Error(`SECRET_NOT_CONFIGURED:${name}`); return value; } }
export interface ProviderEndpointMap { health?:string; initiateVend:string; getVendStatus:string; getTransaction?:string; initiateRefund?:string; getRefundStatus?:string; resendToken?:string; devices?:string; deviceStatus?:string; settlements?:string; }
export interface ProviderFieldMap { providerTransactionId?:string; providerRefundId?:string; vendStatus?:string; transactionStatus?:string; paymentStatus?:string; refundStatus?:string; providerStatus?:string; fulfilment?:string; eventId?:string; eventType?:string; occurredAt?:string; correlationId?:string; eventProviderTransactionId?:string; settlementsArray?:string; settlementId?:string; settlementCurrency?:string; settlementGrossAmount?:string; settlementNetAmount?:string; settlementStatus?:string; settlementPeriodStart?:string; settlementPeriodEnd?:string; settlementTransactionReferences?:string; }
export type NormalizedRefundStatus="PENDING"|"COMPLETED"|"FAILED";
export interface ProviderHttpRuntimeConfiguration { endpoints:ProviderEndpointMap; fields?:ProviderFieldMap; statusMap?:Record<string,VendStatus>; eventStatusMap?:Record<string,VendStatus>; refundStatusMap?:Record<string,NormalizedRefundStatus>; routing?:{requireMerchantMapping?:boolean;requireSiteMapping?:boolean}; auth?:{headerName?:string;prefix?:string}; webhook?:{signatureHeader?:string;timestampHeader?:string;algorithm?:"sha256"|"sha512";signaturePrefix?:string;maxAgeSeconds?:number;includeTimestampInSignature?:boolean;requireTimestamp?:boolean}; }
export function getByPath(value:unknown,path?:string):unknown{if(!path)return undefined;let current:unknown=value;for(const segment of path.split(".")){if(!current||typeof current!=="object")return undefined;current=(current as Record<string,unknown>)[segment];}return current;}
export function interpolatePath(path:string,values:Record<string,string>):string{return path.replace(/\{([a-zA-Z0-9_]+)\}/g,(_m,key:string)=>encodeURIComponent(values[key]??""));}
export function parseRuntimeConfiguration(connector:ConnectorRecord):ProviderHttpRuntimeConfiguration{const raw=connector.runtimeConfiguration;if(!raw||typeof raw!=="object")throw new Error("CONNECTOR_RUNTIME_CONFIGURATION_REQUIRED");const endpoints=(raw as Record<string,unknown>).endpoints;if(!endpoints||typeof endpoints!=="object")throw new Error("CONNECTOR_ENDPOINTS_REQUIRED");const initiateVend=(endpoints as Record<string,unknown>).initiateVend;const getVendStatus=(endpoints as Record<string,unknown>).getVendStatus;if(typeof initiateVend!=="string"||typeof getVendStatus!=="string")throw new Error("CONNECTOR_VENDING_ENDPOINTS_REQUIRED");return raw as unknown as ProviderHttpRuntimeConfiguration;}
export async function buildAuthHeaders(connector:ConnectorRecord,resolver:SecretResolver,runtime:ProviderHttpRuntimeConfiguration):Promise<Record<string,string>>{if(connector.authType==="NONE")return{};if(!connector.credentialReference)throw new Error("CONNECTOR_CREDENTIAL_REFERENCE_REQUIRED");const secret=await resolver.resolve(connector.credentialReference);const headerName=runtime.auth?.headerName??"authorization";const prefix=runtime.auth?.prefix??(connector.authType==="API_KEY"?"Bearer ":"");return{[headerName]:`${prefix}${secret}`};}
export async function requestJson(connector:ConnectorRecord,resolver:SecretResolver,runtime:ProviderHttpRuntimeConfiguration,method:"GET"|"POST",endpoint:string,body?:unknown):Promise<{body:unknown;latencyMs:number;status:number}>{const url=new URL(endpoint,connector.baseUrl).toString();const headers=await buildAuthHeaders(connector,resolver,runtime);headers.accept="application/json";if(body!==undefined)headers["content-type"]="application/json";const start=Date.now();const response=await fetch(url,{method,headers,...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(connector.timeoutMs)});const latencyMs=Date.now()-start;const text=await response.text();let parsed:unknown={};if(text){try{parsed=JSON.parse(text)}catch{parsed={raw:text}}}if(!response.ok){const error=new Error(`PROVIDER_HTTP_${response.status}`);Object.assign(error,{providerResponse:parsed,httpStatus:response.status});throw error;}return{body:parsed,latencyMs,status:response.status};}
export function normalizeVendStatus(rawStatus:unknown,statusMap?:Record<string,VendStatus>):VendStatus{if(typeof rawStatus!=="string")return"UNKNOWN";const normalized=rawStatus.trim().toUpperCase();if(statusMap?.[rawStatus])return statusMap[rawStatus]!;if(statusMap?.[normalized])return statusMap[normalized]!;const allowed:VendStatus[]=["CREATED","SUBMITTED","ACCEPTED","FULFILLED","FAILED","UNKNOWN","CANCELLED"];return allowed.includes(normalized as VendStatus)?normalized as VendStatus:"UNKNOWN";}
export function normalizeRefundStatus(rawStatus:unknown,statusMap?:Record<string,NormalizedRefundStatus>):NormalizedRefundStatus{if(typeof rawStatus!=="string")return"PENDING";const normalized=rawStatus.trim().toUpperCase();if(statusMap?.[rawStatus])return statusMap[rawStatus]!;if(statusMap?.[normalized])return statusMap[normalized]!;if(["COMPLETED","SUCCESS","SUCCEEDED","REFUNDED"].includes(normalized))return"COMPLETED";if(["FAILED","ERROR","REJECTED","CANCELLED"].includes(normalized))return"FAILED";return"PENDING";}
export function sha256(rawBody:string){return createHash("sha256").update(rawBody).digest("hex");}
function headerValue(headers:Record<string,string|string[]|undefined>,name:string){const entry=Object.entries(headers).find(([key])=>key.toLowerCase()===name.toLowerCase())?.[1];return Array.isArray(entry)?entry[0]:entry;}
export async function verifyHmacWebhook(connector:ConnectorRecord,resolver:SecretResolver,headers:Record<string,string|string[]|undefined>,rawBody:string):Promise<boolean>{if(!connector.webhookSecretReference)return false;const runtime=parseRuntimeConfiguration(connector);const webhook=runtime.webhook??{};const signature=headerValue(headers,webhook.signatureHeader??"x-signature");if(!signature)return false;const timestamp=headerValue(headers,webhook.timestampHeader??"x-timestamp");if((webhook.requireTimestamp??true)&&!timestamp)return false;if(timestamp){const numeric=Number(timestamp);const epochMs=Number.isFinite(numeric)?(numeric<10_000_000_000?numeric*1000:numeric):Date.parse(timestamp);if(!Number.isFinite(epochMs))return false;if(Math.abs(Date.now()-epochMs)>(webhook.maxAgeSeconds??300)*1000)return false;}const secret=await resolver.resolve(connector.webhookSecretReference);const signed=webhook.includeTimestampInSignature!==false&&timestamp?`${timestamp}.${rawBody}`:rawBody;const expected=createHmac(webhook.algorithm??"sha256",secret).update(signed).digest("hex");const prefix=webhook.signaturePrefix??"";const supplied=signature.startsWith(prefix)?signature.slice(prefix.length):signature;if(supplied.length!==expected.length)return false;return timingSafeEqual(Buffer.from(supplied),Buffer.from(expected));}
