import { z } from "zod";

export const ProviderStatusSchema = z.enum(["DRAFT","DEVELOPMENT","SANDBOX","CERTIFIED","PRODUCTION","DEGRADED","SUSPENDED","MAINTENANCE","RETIRED"]);
export type ProviderStatus = z.infer<typeof ProviderStatusSchema>;
export const ProviderScopeSchema = z.enum(["PLATFORM","TENANT"]); export type ProviderScope = z.infer<typeof ProviderScopeSchema>;
export const ProviderTypeSchema = z.enum(["NATIVE","CPAY","DIRECT_API","UTILITY","AIRTIME","VENDING_MACHINE","AGGREGATOR","CUSTOM"]); export type ProviderType = z.infer<typeof ProviderTypeSchema>;
export const ConnectorEnvironmentSchema = z.enum(["DEVELOPMENT","SANDBOX","STAGING","PRODUCTION"]); export type ConnectorEnvironment = z.infer<typeof ConnectorEnvironmentSchema>;
export const ConnectorStatusSchema = z.enum(["ACTIVE","DISABLED","DEGRADED","OUTAGE","MAINTENANCE"]); export type ConnectorStatus = z.infer<typeof ConnectorStatusSchema>;
export const ConnectorAuthTypeSchema = z.enum(["NONE","API_KEY","OAUTH2","BASIC","HMAC","MTLS","CUSTOM"]); export type ConnectorAuthType = z.infer<typeof ConnectorAuthTypeSchema>;
export const TransactionStatusSchema = z.enum(["CREATED","PAYMENT_PENDING","PAID","SUBMITTED","ACCEPTED","FULFILLED","SETTLED","FAILED","UNKNOWN","TIMED_OUT","CANCELLED","REVERSED","REFUND_PENDING","REFUNDED","DISPUTED"]); export type TransactionStatus = z.infer<typeof TransactionStatusSchema>;
export const PaymentStatusSchema = z.enum(["CREATED","PENDING","SUCCESS","FAILED","CANCELLED","REVERSED","EXPIRED","UNKNOWN"]); export type PaymentStatus = z.infer<typeof PaymentStatusSchema>;
export const VendStatusSchema = z.enum(["CREATED","SUBMITTED","ACCEPTED","FULFILLED","FAILED","UNKNOWN","CANCELLED"]); export type VendStatus = z.infer<typeof VendStatusSchema>;
export const ProviderHealthStatusSchema = z.enum(["HEALTHY","DEGRADED","OUTAGE","MAINTENANCE","UNKNOWN"]); export type ProviderHealthStatus = z.infer<typeof ProviderHealthStatusSchema>;
export const CapabilityCodeSchema = z.string().min(3).max(128).regex(/^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$/);
export const PrincipalSchema = z.object({ userId:z.uuid(), tenantId:z.uuid(), email:z.email().optional(), displayName:z.string().min(1).max(200).optional(), isPlatformAdmin:z.boolean(), permissions:z.array(CapabilityCodeSchema) }); export type Principal = z.infer<typeof PrincipalSchema>;
export const ProviderCreateInputSchema = z.object({ code:z.string().min(2).max(64).regex(/^[A-Z0-9_]+$/), name:z.string().min(2).max(200), legalName:z.string().min(2).max(250).optional(), providerType:ProviderTypeSchema, scope:ProviderScopeSchema.default("TENANT"), country:z.string().length(2).toUpperCase().optional(), supportedCurrencies:z.array(z.string().length(3).toUpperCase()).default([]), supportedRegions:z.array(z.string().min(1).max(100)).default([]), slaTier:z.string().max(50).optional() }); export type ProviderCreateInput = z.infer<typeof ProviderCreateInputSchema>;
export const ConnectorCreateInputSchema = z.object({ name:z.string().min(2).max(200), environment:ConnectorEnvironmentSchema, apiVersion:z.string().max(50).optional(), baseUrl:z.url(), authType:ConnectorAuthTypeSchema, credentialReference:z.string().min(3).max(500).optional(), webhookSecretReference:z.string().min(3).max(500).optional(), timeoutMs:z.number().int().min(500).max(120000).default(30000), retryPolicy:z.record(z.string(),z.unknown()).default({}), runtimeConfiguration:z.record(z.string(),z.unknown()).default({}), healthCheckPath:z.string().max(300).optional(), enabled:z.boolean().default(false) }); export type ConnectorCreateInput = z.infer<typeof ConnectorCreateInputSchema>;
export const SetCapabilitiesInputSchema = z.object({ capabilities:z.array(CapabilityCodeSchema).min(1).max(100) }); export type SetCapabilitiesInput = z.infer<typeof SetCapabilitiesInputSchema>;

export interface ProviderRecord { id:string; tenantId:string|null; code:string; name:string; legalName:string|null; providerType:ProviderType; scope:ProviderScope; status:ProviderStatus; country:string|null; supportedCurrencies:string[]; supportedRegions:string[]; slaTier:string|null; createdAt:string; updatedAt:string; }
export interface ConnectorRecord { id:string; providerId:string; name:string; environment:ConnectorEnvironment; apiVersion:string|null; baseUrl:string; authType:ConnectorAuthType; credentialReference:string|null; webhookSecretReference:string|null; timeoutMs:number; retryPolicy:Record<string,unknown>; runtimeConfiguration:Record<string,unknown>; healthCheckPath:string|null; status:ConnectorStatus; enabled:boolean; createdAt:string; updatedAt:string; }
export interface CanonicalTransaction { id:string; reference:string; correlationId:string; tenantId:string; merchantId:string; providerId:string|null; connectorId:string|null; serviceId:string; productId:string|null; siteId:string|null; deviceId:string|null; customerId:string|null; currency:string; amount:string; fees:string; taxes:string; totalAmount:string; status:TransactionStatus; paymentStatus:PaymentStatus; vendStatus:VendStatus; refundStatus:string|null; settlementStatus:string|null; providerStatus:string|null; providerTransactionId:string|null; cpayTransactionId:string|null; paymentReference:string|null; idempotencyKey:string; unknownSince:string|null; lastProviderQueryAt:string|null; createdAt:string; updatedAt:string; completedAt:string|null; }
