import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { requirePermission } from "../auth.js";
import { assignRole,createTenantRole,provisionUser,removeRole,setUserStatus } from "../repositories/admin-repository.js";
const bad=(reply:any,p:any)=>reply.code(400).send({error:"VALIDATION_ERROR",issues:p.error.issues});
export async function registerAdminRoutes(app:FastifyInstance):Promise<void>{
 app.post('/api/v1/admin/users',{preHandler:[app.authenticate,requirePermission('user.manage')]},async(r,reply)=>{const p=z.object({email:z.email(),displayName:z.string().min(1).max(200).optional(),isPlatformAdmin:z.boolean().optional()}).safeParse(r.body);if(!p.success)return bad(reply,p);try{return reply.code(201).send({data:await provisionUser(r.principal!,p.data)})}catch(e){return reply.code(409).send({error:'USER_PROVISION_FAILED',message:e instanceof Error?e.message:'Unknown error'})}});
 app.patch('/api/v1/admin/users/:userId',{preHandler:[app.authenticate,requirePermission('user.manage')]},async(r,reply)=>{const p=z.object({status:z.enum(['ACTIVE','SUSPENDED','DISABLED'])}).safeParse(r.body);if(!p.success)return bad(reply,p);try{return{data:await setUserStatus(r.principal!,(r.params as {userId:string}).userId,p.data.status)}}catch(e){return reply.code(409).send({error:'USER_UPDATE_FAILED',message:e instanceof Error?e.message:'Unknown error'})}});
 app.post('/api/v1/admin/users/:userId/roles/:roleId',{preHandler:[app.authenticate,requirePermission('role.manage')]},async(r,reply)=>{const q=r.params as {userId:string;roleId:string};try{return{data:await assignRole(r.principal!,q.userId,q.roleId)}}catch(e){return reply.code(409).send({error:'ROLE_ASSIGN_FAILED',message:e instanceof Error?e.message:'Unknown error'})}});
 app.delete('/api/v1/admin/users/:userId/roles/:roleId',{preHandler:[app.authenticate,requirePermission('role.manage')]},async(r,reply)=>{const q=r.params as {userId:string;roleId:string};try{return{data:await removeRole(r.principal!,q.userId,q.roleId)}}catch(e){return reply.code(409).send({error:'ROLE_REMOVE_FAILED',message:e instanceof Error?e.message:'Unknown error'})}});
 app.post('/api/v1/admin/roles',{preHandler:[app.authenticate,requirePermission('role.manage')]},async(r,reply)=>{const p=z.object({code:z.string().min(2).max(100),name:z.string().min(2).max(150),description:z.string().max(1000).optional(),permissions:z.array(z.string().min(3).max(128)).max(200).default([])}).safeParse(r.body);if(!p.success)return bad(reply,p);try{return reply.code(201).send({data:await createTenantRole(r.principal!,p.data)})}catch(e){return reply.code(409).send({error:'ROLE_CREATE_FAILED',message:e instanceof Error?e.message:'Unknown error'})}});
}
