import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { ConnectorEnvironmentSchema } from "@nolivendaz/canonical-models";
import { EnvironmentSecretResolver } from "@nolivendaz/provider-sdk";
import { executeRefundSafely,fetchProviderSettlements } from "@nolivendaz/provider-orchestrator";
import { requirePermission } from "../auth.js";
import { connectorHasCapability,getConnectorRuntime } from "../repositories/provider-runtime-repository.js";
import { approveRefund,listRefunds,listSettlements,recordRefundResult,requestRefund,upsertSettlements } from "../repositories/phase3-repository.js";
const secrets=new EnvironmentSecretResolver();
const environmentResult=ConnectorEnvironmentSchema.safeParse((process.env.PROVIDER_RUNTIME_ENV??"PRODUCTION").toUpperCase());
if(!environmentResult.success)throw new Error("INVALID_PROVIDER_RUNTIME_ENV");
const requiredEnvironment=environmentResult.data;
const amount=z.string().regex(/^\d+(\.\d{1,6})?$/).refine(v=>Number(v)>0,"Amount must be greater than zero");
const refundSchema=z.object({amount,reason:z.string().min(5).max(1000),idempotencyKey:z.string().min(8).max(200)});
export async function registerFinancialRoutes(app:FastifyInstance){
app.post("/api/v1/transactions/:transactionId/refunds",{preHandler:[app.authenticate,requirePermission("refund.request")]},async(req,reply)=>{const p=refundSchema.safeParse(req.body);if(!p.success)return reply.code(400).send({error:"VALIDATION_ERROR",issues:p.error.issues});try{return reply.code(201).send({data:await requestRefund(req.principal!,(req.params as {transactionId:string}).transactionId,p.data)});}catch(e){return reply.code(409).send({error:"REFUND_REQUEST_FAILED",message:e instanceof Error?e.message:"Unknown error"});}});
app.post("/api/v1/refunds/:refundId/approve",{preHandler:[app.authenticate,requirePermission("refund.approve")]},async(req,reply)=>{try{const r=await approveRefund(req.principal!,(req.params as {refundId:string}).refundId);if(r.connector.environment!==requiredEnvironment)throw new Error(`CONNECTOR_ENVIRONMENT_MISMATCH:${r.connector.environment}:${requiredEnvironment}`);const enabled=await connectorHasCapability(req.principal!,r.connector.id,"refund.create");const result=enabled?await executeRefundSafely(r.providerType,r.connector,secrets,{transactionId:r.transactionId,providerTransactionId:r.providerTransactionId,amount:r.amount,currency:r.currency,reason:r.reason,idempotencyKey:r.idempotencyKey}):{outcome:"FAILED" as const,error:"CONNECTOR_CAPABILITY_REFUND_CREATE_NOT_ENABLED"};await recordRefundResult(req.principal!,r.refundId,r.transactionId,result);return reply.code(result.outcome==="FAILED"?422:202).send({data:{refundId:r.refundId,outcome:result.outcome,...(result.outcome==="CONFIRMED"?{providerRefundId:result.response.providerRefundId,status:result.response.status}:{error:result.error})}});}catch(e){return reply.code(409).send({error:"REFUND_APPROVAL_FAILED",message:e instanceof Error?e.message:"Unknown error"});}});
app.get("/api/v1/refunds",{preHandler:[app.authenticate,requirePermission("refund.read")]},async req=>({data:await listRefunds(req.principal!,100)}));
app.post("/api/v1/providers/:providerId/settlements/sync",{preHandler:[app.authenticate,requirePermission("settlement.sync")]},async(req,reply)=>{const q=z.object({from:z.iso.datetime(),to:z.iso.datetime()}).refine(v=>Date.parse(v.to)>Date.parse(v.from),{message:"to must be after from",path:["to"]}).safeParse(req.query);if(!q.success)return reply.code(400).send({error:"VALIDATION_ERROR",issues:q.error.issues});try{const runtime=await getConnectorRuntime(req.principal!,(req.params as {providerId:string}).providerId);if(runtime.connector.environment!==requiredEnvironment)throw new Error(`CONNECTOR_ENVIRONMENT_MISMATCH:${runtime.connector.environment}:${requiredEnvironment}`);if(!(await connectorHasCapability(req.principal!,runtime.connector.id,"settlement.list")))throw new Error("CONNECTOR_CAPABILITY_SETTLEMENT_LIST_NOT_ENABLED");const rows=await fetchProviderSettlements(runtime.connector,secrets,q.data.from,q.data.to);const count=await upsertSettlements(req.principal!,runtime.providerId,runtime.connector.id,rows);return{data:{synced:count,providerId:runtime.providerId}};}catch(e){return reply.code(409).send({error:"SETTLEMENT_SYNC_FAILED",message:e instanceof Error?e.message:"Unknown error"});}});
app.get("/api/v1/settlements",{preHandler:[app.authenticate,requirePermission("settlement.read")]},async req=>({data:await listSettlements(req.principal!,100)}));
}
