import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { requirePermission } from "../auth.js";
import * as repo from "../repositories/management-repository.js";

const code=z.string().trim().min(2).max(100).transform(v=>v.toUpperCase());
const money=z.string().regex(/^\d+(\.\d{1,6})?$/).optional();
function bad(reply:any,parsed:any){return reply.code(400).send({error:"VALIDATION_ERROR",issues:parsed.error.issues});}
export async function registerManagementRoutes(app:FastifyInstance):Promise<void>{
 app.get('/api/v1/merchants',{preHandler:[app.authenticate,requirePermission('merchant.read')]},async r=>({data:await repo.listMerchants(r.principal!)}));
 app.post('/api/v1/merchants',{preHandler:[app.authenticate,requirePermission('merchant.manage')]},async(r,reply)=>{const p=z.object({code,name:z.string().min(2).max(200),legalName:z.string().max(250).optional(),country:z.string().length(2).optional(),currency:z.string().length(3).optional()}).safeParse(r.body);if(!p.success)return bad(reply,p);try{return reply.code(201).send({data:await repo.createMerchant(r.principal!,p.data)})}catch(e){return reply.code(409).send({error:'MERCHANT_CREATE_FAILED',message:e instanceof Error?e.message:'Unknown error'})}});
 app.get('/api/v1/sites',{preHandler:[app.authenticate,requirePermission('merchant.read')]},async r=>({data:await repo.listSites(r.principal!,(r.query as {merchantId?:string}).merchantId)}));
 app.post('/api/v1/sites',{preHandler:[app.authenticate,requirePermission('merchant.manage')]},async(r,reply)=>{const p=z.object({merchantId:z.uuid(),code,name:z.string().min(2).max(200),address:z.string().max(1000).optional(),district:z.string().max(120).optional(),region:z.string().max(120).optional(),timezone:z.string().max(100).optional()}).safeParse(r.body);if(!p.success)return bad(reply,p);try{return reply.code(201).send({data:await repo.createSite(r.principal!,p.data)})}catch(e){return reply.code(409).send({error:'SITE_CREATE_FAILED',message:e instanceof Error?e.message:'Unknown error'})}});
 app.get('/api/v1/services',{preHandler:[app.authenticate,requirePermission('catalog.read')]},async r=>({data:await repo.listServices(r.principal!)}));
 app.post('/api/v1/services',{preHandler:[app.authenticate,requirePermission('catalog.manage')]},async(r,reply)=>{const p=z.object({code,name:z.string().min(2).max(200),category:z.string().min(2).max(80)}).safeParse(r.body);if(!p.success)return bad(reply,p);return reply.code(201).send({data:await repo.createService(r.principal!,p.data)});});
 app.get('/api/v1/products',{preHandler:[app.authenticate,requirePermission('catalog.read')]},async r=>({data:await repo.listProducts(r.principal!)}));
 app.post('/api/v1/products',{preHandler:[app.authenticate,requirePermission('catalog.manage')]},async(r,reply)=>{const p=z.object({serviceId:z.uuid(),code,name:z.string().min(2).max(200),currency:z.string().length(3).optional(),minAmount:money,maxAmount:money,fixedPrice:money,variableAmountAllowed:z.boolean().optional()}).safeParse(r.body);if(!p.success)return bad(reply,p);try{return reply.code(201).send({data:await repo.createProduct(r.principal!,p.data)})}catch(e){return reply.code(409).send({error:'PRODUCT_CREATE_FAILED',message:e instanceof Error?e.message:'Unknown error'})}});
 app.get('/api/v1/routes',{preHandler:[app.authenticate,requirePermission('route.read')]},async r=>({data:await repo.listRoutes(r.principal!)}));
 app.post('/api/v1/routes',{preHandler:[app.authenticate,requirePermission('route.manage')]},async(r,reply)=>{const p=z.object({merchantId:z.uuid().optional(),serviceId:z.uuid(),productId:z.uuid().optional(),country:z.string().length(2).optional(),region:z.string().max(120).optional(),currency:z.string().length(3).optional(),primaryProviderId:z.uuid(),secondaryProviderId:z.uuid().optional(),priority:z.number().int().min(1).max(10000).optional(),effectiveFrom:z.iso.datetime().optional(),effectiveTo:z.iso.datetime().optional()}).safeParse(r.body);if(!p.success)return bad(reply,p);try{return reply.code(201).send({data:await repo.createRoute(r.principal!,p.data)})}catch(e){return reply.code(409).send({error:'ROUTE_CREATE_FAILED',message:e instanceof Error?e.message:'Unknown error'})}});
 app.get('/api/v1/devices',{preHandler:[app.authenticate,requirePermission('device.read')]},async r=>({data:await repo.listDevices(r.principal!)}));
 app.get('/api/v1/payments',{preHandler:[app.authenticate,requirePermission('payment.read')]},async r=>({data:await repo.listPayments(r.principal!)}));
 app.get('/api/v1/alerts',{preHandler:[app.authenticate,requirePermission('alert.read')]},async r=>({data:await repo.listAlerts(r.principal!)}));
 app.patch('/api/v1/alerts/:alertId',{preHandler:[app.authenticate,requirePermission('alert.manage')]},async(r,reply)=>{const p=z.object({status:z.enum(['ACKNOWLEDGED','RESOLVED','SUPPRESSED'])}).safeParse(r.body);if(!p.success)return bad(reply,p);try{return{data:await repo.setAlertStatus(r.principal!,(r.params as {alertId:string}).alertId,p.data.status)}}catch(e){return reply.code(404).send({error:'ALERT_NOT_FOUND'})}});
 app.get('/api/v1/incidents',{preHandler:[app.authenticate,requirePermission('incident.read')]},async r=>({data:await repo.listIncidents(r.principal!)}));
 app.post('/api/v1/incidents',{preHandler:[app.authenticate,requirePermission('incident.manage')]},async(r,reply)=>{const p=z.object({title:z.string().min(3).max(240),severity:z.enum(['LOW','MEDIUM','HIGH','CRITICAL']),summary:z.string().max(5000).optional(),providerId:z.uuid().optional(),connectorId:z.uuid().optional()}).safeParse(r.body);if(!p.success)return bad(reply,p);return reply.code(201).send({data:await repo.createIncident(r.principal!,p.data)});});
 app.get('/api/v1/analytics/summary',{preHandler:[app.authenticate,requirePermission('analytics.read')]},async r=>({data:await repo.analyticsSummary(r.principal!)}));
 app.get('/api/v1/admin/users',{preHandler:[app.authenticate,requirePermission('admin.user.read')]},async r=>({data:await repo.listUsers(r.principal!)}));
 app.get('/api/v1/admin/roles',{preHandler:[app.authenticate,requirePermission('admin.role.read')]},async r=>({data:await repo.listRoles(r.principal!)}));
 app.get('/api/v1/admin/audit',{preHandler:[app.authenticate,requirePermission('admin.audit.read')]},async r=>({data:await repo.listAudit(r.principal!)}));
}
