import "server-only";
import { randomUUID } from "node:crypto";
import { cookies, headers } from "next/headers";

const baseUrl=(process.env.BACKOFFICE_API_URL??"http://localhost:4000").replace(/\/$/,"");
export class BackOfficeApiError extends Error{constructor(readonly status:number,message:string,readonly code?:string){super(message);}}
async function authorizationHeader():Promise<string>{const h=await headers();const forwarded=h.get("authorization");if(forwarded?.startsWith("Bearer "))return forwarded;const cs=await cookies();const token=cs.get("nolivendaz_access_token")?.value;if(token)return`Bearer ${token}`;if(process.env.NODE_ENV!=="production"&&process.env.BACKOFFICE_DEV_BEARER_TOKEN)return`Bearer ${process.env.BACKOFFICE_DEV_BEARER_TOKEN}`;throw new BackOfficeApiError(401,"Operator session is not available","OPERATOR_SESSION_REQUIRED");}
async function request<T>(path:string,init?:RequestInit):Promise<T>{const incoming=await headers();const correlationId=incoming.get("x-correlation-id")??randomUUID();const authorization=await authorizationHeader();const requestHeaders=new Headers(init?.headers);requestHeaders.set("accept","application/json");requestHeaders.set("authorization",authorization);requestHeaders.set("x-correlation-id",correlationId);if(init?.body)requestHeaders.set("content-type","application/json");const response=await fetch(`${baseUrl}${path}`,{...init,cache:"no-store",headers:requestHeaders});const text=await response.text();let payload:unknown={};if(text){try{payload=JSON.parse(text)}catch{payload={message:text}}}if(!response.ok){const o=payload&&typeof payload==="object"?payload as Record<string,unknown>:{};const code=typeof o.error==="string"?o.error:undefined;throw new BackOfficeApiError(response.status,typeof o.message==="string"?o.message:`API request failed (${response.status})`,code);}return payload as T;}
export async function apiGet<T>(path:string):Promise<T>{return(await request<{data:T}>(path)).data;}
export async function apiPost<T=unknown>(path:string,body?:unknown):Promise<T>{return(await request<{data:T}>(path,{method:"POST",...(body===undefined?{}:{body:JSON.stringify(body)})})).data;}
export async function apiPatch<T=unknown>(path:string,body:unknown):Promise<T>{return(await request<{data:T}>(path,{method:"PATCH",body:JSON.stringify(body)})).data;}
