export interface OperatorContext{userId:string;tenantId:string;displayName?:string;email?:string;isPlatformAdmin:boolean;permissions:string[]}
export interface OperationsQueues{unknown_transactions?:number;unknown_value?:string;refund_required?:number;refund_required_value?:string;reconciliation_open?:number;support_open?:number;provider_outages?:number;certification_failures?:number;[key:string]:unknown}
export interface TransactionSummary{id:string;reference:string;correlationId:string;merchantName?:string;providerName?:string;connectorName?:string;serviceName?:string;productName?:string;siteName?:string;currency:string;amount:string;totalAmount:string;status:string;paymentStatus:string;vendStatus:string;refundStatus?:string|null;settlementStatus?:string|null;providerTransactionId?:string|null;refundRequired?:boolean;settlementBlocked?:boolean;financialHoldReason?:string|null;createdAt:string;updatedAt:string;[key:string]:unknown}
export interface Transaction360 extends TransactionSummary{connectorId?:string|null;providerId?:string|null;paymentReference?:string|null;cpayTransactionId?:string|null;recoveryAttempts?:number;nextRecoveryAt?:string|null;recoveryLastError?:string|null;routing?:Array<Record<string,unknown>>;refunds?:Array<Record<string,unknown>>;reconciliationExceptions?:Array<Record<string,unknown>>;supportCases?:Array<Record<string,unknown>>;settlementMatches?:Array<Record<string,unknown>>;timeline?:Array<Record<string,unknown>>}
export interface ProviderSummary{id:string;code:string;name:string;providerType:string;scope:string;status:string;country?:string|null;supportedCurrencies?:string[];supportedRegions?:string[];[key:string]:unknown}
export interface ProviderConnector{id:string;name:string;environment:string;apiVersion?:string|null;baseUrl:string;authType:string;timeoutMs:number;status:string;enabled:boolean;capabilities:string[];healthStatus?:string|null;healthLatencyMs?:number|null;healthCheckedAt?:string|null;certificationStatus?:string|null;certificationRunId?:string|null}
export interface ProviderOperations{provider:ProviderSummary;connectors:ProviderConnector[]}
export interface ConnectorCapabilities{id:string;providerId:string;name:string;environment:string;status:string;enabled:boolean;capabilities:string[]}
export interface SupportCase{id:string;case_number?:string;category:string;priority:string;status:string;title:string;description?:string|null;transaction_id?:string|null;provider_name?:string|null;transaction_reference?:string|null;opened_at?:string;updated_at?:string;[key:string]:unknown}
export interface CustomerIdentityRecord{id:string;external_reference:string;phone?:string|null;email?:string|null;display_name?:string|null;status:string;phone_verified_at?:string|null;identity_type?:string|null;identity_country?:string|null;identity_number_mask?:string|null;identity_status:string;identity_provider?:string|null;identity_provider_reference?:string|null;identity_verified_at?:string|null;consent_version?:string|null;consent_accepted_at?:string|null;identity_source?:string|null;identity_source_updated_at?:string|null;identity_last_synced_at?:string|null;profile_setup_complete:boolean;terms_accepted:boolean;identity_configured:boolean;identity_consent_accepted:boolean;service_access_policy_version?:string|null;service_access_source?:string|null;service_access_synced_at?:string|null;protected_service_access:string;protected_service_allowed:boolean;protected_service_missing:string[];protected_service:string;created_at:string;updated_at:string}
export interface IdentityProviderCapability{id:string;provider_code:string;enabled:boolean;supports_sync:boolean;supports_async:boolean;supported_identity_types:string[];supported_countries:string[];source:string;source_reference?:string|null;source_updated_at:string;last_synced_at:string;created_at:string;updated_at:string}
export interface CustomerServiceAccessPolicy{service:string;baselineVersion:string;requirements:Array<{code:string;label:string}>}
